version: "3"
 
services:
  app:
    image: node:16
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
    working_dir: /app
    # command: sh -c 'npx tsc; npx tsc --watch ./**/*.ts; npm run dev'
    command: sh -c 'npx tsc; npm run dev'

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8000:8000
    volumes:
      - ./database:/docker-entrypoint.db