version: "3"
 
services:
  app:
    image: node:16
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
    working_dir: /app
    command: sh -c 'npm run dev && npx tsc --watch' ## for dev
    # command: sh -c 'npm run start' ## for show off

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8000:8000
    volumes:
      - ./database:/docker-entrypoint.db